# Site settings
title: Molly The Fiddler
email: thompsonmollym@gmail.com
description: "Molly is an active Irish fiddler in Western Pennsylvania and Ohio, primarily influenced by the Donegal tradition."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mollythefiddler.com" # the base hostname & protocol for your site

collections:
  - sections

twitter_username:
github_username:

# Add your google-analytics ID here to activate google analytics
# google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/